export const ERROR_CODE = {
  // Common
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  INVALID_PARAMETER: 'INVALID_PARAMETER',

  // Auth
  ALREADY_USED_EMAIL: 'ALREADY_USED_EMAIL',
  INVALID_LOGIN_DATA: 'INVALID_LOGIN_DATA',
  INVALID_UUID: 'INVALID_UUID',
  INVALID_VERIFICATION_CODE: 'INVALID_VERIFICATION_CODE',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  // City
  CITY_NOT_FOUND: 'CITY_NOT_FOUND',
  // EmailVerification
  EMAIL_VERIFICATION_NOT_FOUND: 'EMAIL_VERIFICATION_NOT_FOUND',
  EMAIL_VERIFICATION_EXPIRED: 'EMAIL_VERIFICATION_EXPIRED',
  // Session
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  // RefreshToken
  REFRESH_TOKEN_NOT_FOUND: 'REFRESH_TOKEN_NOT_FOUND',
  // S3
  S3_UPLOAD_FAILED: 'S3_UPLOAD_FAILED',
  // File
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  // Notification
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  // UserApproval
  USER_APPROVAL_NOT_FOUND: 'USER_APPROVAL_NOT_FOUND',
  // UserVerificationDocument
  USER_VERIFICATION_DOCUMENT_NOT_FOUND: 'USER_VERIFICATION_DOCUMENT_NOT_FOUND',

  INVALID_VISIT_ID: 'INVALID_VISIT_ID',
  INVALID_DATE_FORMAT: 'INVALID_DATE_FORMAT',
  ALREADY_USED_PASSPORT_NUMBER: 'ALREADY_USED_PASSPORT_NUMBER',
};
