import { StyleSheet } from 'react-native';

import { COLOR } from '~/utils/guide';

export default StyleSheet.create({
  container: {
    position: 'absolute',
    flex: 1,
    zIndex: 1,
    width: '100%',
    height: '100%',
    overflow: 'hidden',
  },
  cameraFilter: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    zIndex: 1,
  },
  cameraFilterVertical: {
    width: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  cameraFilterHorizontalWrap: {
    zIndex: 1,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cameraFilterHorizontal: {
    width: '15%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  cameraFilterHorizontalCenter: {
    zIndex: 1,
    width: '70%',
    height: '100%',
  },
  cameraFilterBorderTopLeft: {
    position: 'absolute',
    width: 24,
    height: 20,
    top: -3,
    left: -3,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderTopLeftRadius: 5,
  },
  cameraFilterBorderTopRight: {
    position: 'absolute',
    width: 24,
    height: 20,
    top: -3,
    right: -3,
    borderTopWidth: 4,
    borderRightWidth: 4,
    borderTopRightRadius: 5,
  },
  cameraFilterBorderBottomLeft: {
    position: 'absolute',
    width: 24,
    height: 20,
    bottom: -3,
    left: -3,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    borderBottomLeftRadius: 5,
  },
  cameraFilterBorderBottomRight: {
    position: 'absolute',
    width: 24,
    height: 20,
    bottom: -3,
    right: -3,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderBottomRightRadius: 5,
  },
  cameraFilterCenterWrap: {
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraFilterCenterImage: {
    width: 80,
    height: 80,
  },
  guideText: {
    position: 'absolute',
    zIndex: 2,
    bottom: '20%',
    width: '100%',
    textAlign: 'center',
    color: COLOR.WHITE,
  },
});
